### ISSUE TITLE
Set the correct branch in Settings/Pages/Branch 

### ISSUE THREAD

**Issue by granicz** [Alexaaaaaaaaaaaaaa/midterm-project#1]
It should be set to `gh-pages`, like in this screenshot:

![image](https://github.com/Alexaaaaaaaaaaaaaa/midterm-project/assets/6954755/2da4ac65-401a-459c-b3d2-e11ad198c560)

Once fixed, the public deployment should point to the app, and not to the README.

**Comment by Alexaaaaaaaaaaaaaa** [comment]
its working now, thank you!
